
print("NAME:- SANKET MAHAPATRA")
print("REGISTRATION NUMBER:- 2241013017")

print("""
Classes are fundamental in Python as they enable Object-Oriented Programming (OOP). They serve as blueprints for creating objects, encapsulating data (attributes) and behavior (methods) together.

Significance of Classes in OOP:
1. Encapsulation: Bundles data and methods, restricting direct access to attributes.
2. Abstraction: Hides implementation details, exposing only necessary functionalities.
3. Inheritance: Enables code reuse by allowing child classes to inherit properties and behaviors.
4. Polymorphism: Allows different classes to have methods with the same name but different implementations.
5. Code Reusability & Modularity: Organizes code efficiently for large-scale projects.

""")
